# Generated by Django 4.1.7 on 2023-03-30 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('is_AT', models.BooleanField(default=False, verbose_name='Agent de terrain')),
                ('is_COORD', models.BooleanField(default=False, verbose_name='Coordonnateur')),
                ('is_DG', models.BooleanField(default=False, verbose_name='Directeur General')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'axes',
            },
        ),
        migrations.CreateModel(
            name='Chefferie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chefferies',
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=150, unique=True)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('agrement', models.CharField(max_length=30, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cooperatives',
            },
        ),
        migrations.CreateModel(
            name='Groupement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chefferie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupements', to='cfm_pro_api.chefferie')),
            ],
            options={
                'db_table': 'groupements',
            },
        ),
        migrations.CreateModel(
            name='Minerai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('formule', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'minerais',
            },
        ),
        migrations.CreateModel(
            name='Negociant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('birth_date', models.DateField(blank=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('plot_number', models.CharField(blank=True, max_length=10, null=True)),
                ('card_number', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'negociants',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('groupement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='cfm_pro_api.groupement')),
            ],
            options={
                'db_table': 'villages',
            },
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('authorization', models.CharField(blank=True, max_length=30, unique=True)),
                ('plot_number', models.CharField(blank=True, max_length=10, null=True)),
                ('plates', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfm_pro_api.village')),
                ('negociant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfm_pro_api.negociant')),
            ],
            options={
                'db_table': 'transporteurs',
                'unique_together': {('nom', 'postnom')},
            },
        ),
        migrations.CreateModel(
            name='Territoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territoires', to='cfm_pro_api.province')),
            ],
            options={
                'db_table': 'territoires',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('territoire', models.CharField(max_length=50)),
                ('secteur', models.CharField(blank=True, max_length=50)),
                ('groupement', models.CharField(blank=True, max_length=50)),
                ('localite', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='cfm_pro_api.axe')),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.AddField(
            model_name='negociant',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfm_pro_api.village'),
        ),
        migrations.AddField(
            model_name='chefferie',
            name='territoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefferies', to='cfm_pro_api.territoire'),
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='cfm_pro_api.site')),
            ],
            options={
                'db_table': 'chantiers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='negociant',
            unique_together={('nom', 'postnom')},
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('colis', models.IntegerField()),
                ('poids', models.IntegerField()),
                ('tags', models.TextField()),
                ('atm', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_submit', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(blank=True, default=False)),
                ('date_confirm', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='cfm_pro_api.chantier')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='cfm_pro_api.cooperative')),
                ('minerai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='cfm_pro_api.minerai')),
                ('negociant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='cfm_pro_api.negociant')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='cfm_pro_api.transporteur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lots',
                'ordering': ['date'],
                'unique_together': {('date', 'negociant', 'minerai', 'colis')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('plot_number', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_img_url', models.URLField(blank=True, null=True)),
                ('zone', models.CharField(choices=[('ALL', 'Partout'), ('KIN', 'Kinshasa'), ('GOM', 'Goma'), ('KND', 'Kindu'), ('MSS', 'Masisi'), ('BKV', 'Bukavu')], max_length=20)),
                ('date_signup', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('number_verified', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfm_pro_api.village')),
            ],
            options={
                'db_table': 'profiles',
                'unique_together': {('user', 'email')},
            },
        ),
    ]
