# Generated by Django 4.1.7 on 2023-04-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfm_pro_api', '0002_alter_chantier_latitude_alter_chantier_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporteur',
            old_name='authorization',
            new_name='authorisation',
        ),
    ]
